services:

  postgres:
    container_name: qchat-postgresDB
    image: postgres:14.5-alpine
    user: postgres
    restart: always
    env_file:
      - docker.env
    ports:
      - '5400:5432'
    volumes:
      - qchat-postgres:/var/lib/postgresql/data
    networks:
      - qchat-network

  pgadmin:
    depends_on:
      - postgres
    links:
      - postgres:postgres
    container_name: qchat-pgadminTool
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    volumes:
      - pgadmindata:/root/.pgadmin
      - pgadminlibdata:/var/lib/pgadmin
    env_file:
      - docker.env
    networks:
      - qchat-network


volumes:
  qchat-postgres:
      driver: local
  pgadmindata:
    driver: local
  pgadminlibdata:
    driver: local

networks:
  qchat-network:
    driver: bridge
